---
title: "EDA"
author: ""
date: "June 14, 2018"
output: html_document
---

#Reading in the data
```{r}
library(tidyverse)

sure_path <- substr(getwd(), 1, nchar(getwd()) - 4)
individual_path <- paste(sure_path, "/data/individual_database.csv", sep = "")
individual <- read_csv(individual_path, 
                       col_types = cols(X1 = col_skip(), 
                                        meansOfControlRestrictsFinancialAccess = col_integer(), 
                                        meansOfControlSexualAbuse = col_integer(), 
                                        meansOfControlUsesChildren = col_integer(), 
                                        typeOfSexPornography = col_integer(), 
                                        typeOfSexRemoteInteractiveServices = col_integer(), 
                                        typeOfSexPrivateSexualServices = col_integer()))

#converts year of registration and ageBroad into ordered factors
individual$yearOfRegistration <- as.ordered(individual$yearOfRegistration)
individual$ageBroad <- as.ordered(individual$ageBroad)
individual$ageBroad <- fct_relevel(individual$ageBroad, "0--8", "9--17", 
                                   "18--20", "21--23", "24--26", "27--29", 
                                   "30--38", "39--47", "48+")

#converts the columns with characters into unordered factors
factor_cols <- c("Datasource", "gender", "majorityStatus", "majorityEntry", 
                 "citizenship", "RecruiterRelationship", "CountryOfExploitation")

for (column in factor_cols) {
  individual[,column] <- as.factor(unlist(individual[,column]))
}


country_path <- paste(sure_path, "/data/country_summary_dat.csv", sep = "")
country <- read_csv(country_path, 
                    col_types = cols(X1 = col_skip(),
                                     tier2003 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2004 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2005 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2006 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2007 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2008 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2009 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2010 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2011 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2012 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2013 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2014 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2015 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2016 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     tier2017 = col_factor(c("1", "2", "2w", "3"),
                                                           ordered = TRUE),
                                     poverty2015 = col_double(), 
                                     poverty2016 = col_double(), 
                                     poverty2017 = col_double(), 
                                     poverty2018 = col_double(), 
                                     gender2006 = col_double(), 
                                     gender2007 = col_double(), 
                                     gender2008 = col_double(), 
                                     gender2009 = col_double(), 
                                     gender2010 = col_double(), 
                                     gender2011 = col_double(), 
                                     gender2012 = col_double(), 
                                     gender2013 = col_double(), 
                                     gender2014 = col_double(), 
                                     gender2015 = col_double(), 
                                     gender2016 = col_double(), 
                                     gender2017 = col_double(), 
                                     gdp_per_capita2017 = col_double()),
                    na = c("", "NA", "N/A", "-")
  
)


population_path <- paste(sure_path, "/data/population.csv", sep = "")
population <- read_csv(population_path, 
                       col_types = cols(X1 = col_skip()))

#readr has trouble reading the numbers in their original format
population[,-(1:2)] <- sapply(population[,-(1:2)], str_replace_all, " ", "")
population[,-(1:2)] <- sapply(population[,-(1:2)], str_replace, "[.]", "")
population[,-(1:2)] <- sapply(population[,-(1:2)], as.numeric)


migration_path <- paste(sure_path, "/data/migration.csv", sep = "")
migration <- read_csv(migration_path, col_types = cols(X1 = col_skip()))

migration$value <- str_replace_all(migration$value, "[..]", "0")
migration$value <- str_replace_all(migration$value, ",", "")
#will throw an "NAs introduced by coercion" error but I think those rows have 
#NAs in the original dataset and the error is safe to ignore
migration$value <- as.numeric(migration$value) 
```

#Imani 
```{r}
library(reshape2)
#dataset of poverty
poverty.data <- select(country, Country.y:Country.x, 
                     poverty1990:poverty2018)


names(poverty.data)[3:31]=c("1990","1991","1992","1993","1994","1995","1996",
                            "1997","1998","1999","2000","2001","2002","2003",
                            "2004","2005","2006","2007","2008","2009","2010",
                            "2011","2012","2013","2014","2015","2016","2017",
                            "2018")
poverty.data <- poverty.data %>% melt(id = c("Country.x","Country.y"))

```


#Shiva
```{r}
#
ggplot(data = individual, aes(x = ageBroad, fill = gender)) + 
  geom_bar(position = "fill") + facet_wrap(~individual$isSexualExploit) + 
  labs(title = "Gender and Age Faceted by isSexualExploit", x = "Age Range", 
       y = "proportion") + 
  theme(axis.text.x = element_text(size = 10, angle = 90), 
        plot.title = element_text(face = "bold", hjust = 0.5))


ggplot(data = individual, aes(x = ageBroad, fill = gender)) + 
  geom_bar(position = "fill") + facet_wrap(~individual$isForcedLabour) + 
  labs(title = "Gender and Age Faceted by isForcedLabour", x = "Age Range", 
       y = "proportion") + 
  theme(axis.text.x = element_text(size = 10, angle = 90), 
        plot.title = element_text(face = "bold", hjust = 0.5))



#Combines country GDP and Poverty rates from 1990-2016 into a data frame
country_GDPvPoverty <- data.frame("Country" = character(), "Year" = integer(), 
                                  "Poverty" = double(),
                                  "GDP" = double())
for (i in 1:nrow(country)){
  for (j in 1990:2016) {
    new_row <- data.frame(base::rbind(c(country[i, 1], j, country[i, j-1958],
                                        country[i, j-1887])))
    names(new_row) <- names(country_GDPvPoverty)
    country_GDPvPoverty <- base::rbind(country_GDPvPoverty, new_row)
  }
}

country_GDPvPoverty$Country <- as.character(country_GDPvPoverty$Country)
country_GDPvPoverty$Year <- as.integer(country_GDPvPoverty$Year)
country_GDPvPoverty$Poverty <- as.double(country_GDPvPoverty$Poverty)
country_GDPvPoverty$GDP <- as.double(country_GDPvPoverty$GDP)

model <- lm(Poverty ~ log10(GDP), data = country_GDPvPoverty)

ggplot(data = country_GDPvPoverty, aes(x = GDP, y = Poverty, color = Year)) + 
  geom_abline(slope = coef(model)[2], intercept = coef(model)[1], size = 1) + 
  geom_point() + geom_smooth(method = 'lm') + scale_x_log10() + 
  scale_colour_gradientn(colours=rainbow(4)) +
  labs(title = "Poverty Rate vs Log10(GDP) from 1990 to 2016") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5))

#producing the heatmap of missingness correlations
library(stats)
source(paste(sure_path, '/functions/na_mat.R', sep = ''))


na_cor0 <- na_mat(individual)[[3]]
stats::heatmap(na_cor0)

individual_filled_in <- individual
#filling in the NAs with zeros in the means of control (9:26), type of 
#exploitation (27:33), and recuiter relationship (54:58) groups of variables 
#where at least one variable in each row of each group has a 1 

for(j in list(9:26, 27:33, 54:58)) {
  for (i in 1:nrow(individual_filled_in[,j])){
    if (sum(individual_filled_in[i,j], na.rm = TRUE)>0){
      individual_filled_in[i,j][as.vector(is.na(individual_filled_in[i,j]))]<-0
    }
  }
}

#heatmap after filling in some of the NAs
na_cor1 <- na_mat(individual_filled_in)[[3]]
stats::heatmap(na_cor1)

```


#Michael 
```{r}
cubic_x <- function(x){x^3}
```


