---
title: "Merging Datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

sure_path <- substr(getwd(), 1, nchar(getwd()) - 4)
individual_path <- paste(sure_path, "/data/individual_database.csv", sep = "")
individual <- read_csv(individual_path, 
                       col_types = cols(X1 = col_skip(), 
                                        meansOfControlRestrictsFinancialAccess = col_integer(), 
                                        meansOfControlSexualAbuse = col_integer(), 
                                        meansOfControlUsesChildren = col_integer(), 
                                        typeOfSexPornography = col_integer(), 
                                        typeOfSexRemoteInteractiveServices = col_integer(), 
                                        typeOfSexPrivateSexualServices = col_integer()))

#converts year of registration and ageBroad into ordered factors
individual$yearOfRegistration <- as.ordered(individual$yearOfRegistration)
individual$ageBroad <- as.ordered(individual$ageBroad)
individual$ageBroad <- fct_relevel(individual$ageBroad, "0--8", "9--17", 
                                   "18--20", "21--23", "24--26", "27--29", 
                                   "30--38", "39--47", "48+")

#converts the columns with characters into unordered factors
factor_cols <- c("Datasource", "gender", "majorityStatus", "majorityEntry", 
                 "citizenship", "RecruiterRelationship", "CountryOfExploitation")

for (column in factor_cols) {
  individual[,column] <- as.factor(unlist(individual[,column]))
}


country_path <- paste(sure_path, "/data/country_summary_dat.csv", sep = "")
country <- read_csv(country_path, 
                    col_types = cols(X1 = col_skip(),
                                     poverty2015 = col_double(), 
                                     poverty2016 = col_double(), 
                                     poverty2017 = col_double(), 
                                     poverty2018 = col_double(), 
                                     gender2006 = col_double(), 
                                     gender2007 = col_double(), 
                                     gender2008 = col_double(), 
                                     gender2009 = col_double(), 
                                     gender2010 = col_double(), 
                                     gender2011 = col_double(), 
                                     gender2012 = col_double(), 
                                     gender2013 = col_double(), 
                                     gender2014 = col_double(), 
                                     gender2015 = col_double(), 
                                     gender2016 = col_double(), 
                                     gender2017 = col_double(), 
                                     gdp_per_capita2017 = col_double()),
                    na = c("", "NA", "N/A")
  
)


population_path <- paste(sure_path, "/data/population.csv", sep = "")
population <- read_csv(population_path, 
                       col_types = cols(X1 = col_skip()))

#readr has trouble reading the numbers in their original format
population[,-(1:2)] <- sapply(population[,-(1:2)], str_replace_all, " ", "")
population[,-(1:2)] <- sapply(population[,-(1:2)], str_replace, "[.]", "")
population[,-(1:2)] <- sapply(population[,-(1:2)], as.numeric)


migration_path <- paste(sure_path, "/data/migration.csv", sep = "")
migration <- read_csv(migration_path, col_types = cols(X1 = col_skip()))

migration$value <- str_replace_all(migration$value, "[..]", "0")
migration$value <- str_replace_all(migration$value, ",", "")
#will throw an "NAs introduced by coercion" error but I think those rows have 
#NAs in the original dataset and the error is safe to ignore
migration$value <- as.numeric(migration$value) 
```

## Shiva

```{r}

```

## Imani 

```{r}
library(tidyverse)

#filling missing values in the country summary data set
sure_path <- substr(getwd(), 1, nchar(getwd()) - 4)
source(paste(sure_path, "/functions/linearly_interpolate.R", sep = ""))
country <- linearly_interpolate(country, list(6:15, 32:60, 61:72, 73:130, 
                                              138:131, 149:139))

#Clearing NA's from cCountry.y by copying a lowercase version of Country.X
country <-country %>% filter(!(is.na(Country.y) & is.na(Country.x)))


country$Country.y= tolower(country$Country.x)

country$Country.y <-str_to_title(country$Country.y)

#melting poverty data

library(reshape2)
poverty_data<-select(country, Country.y:Country.x, `Country Code`, poverty2002:poverty2017)


names(poverty_data)[4:19]=as.character(2002:2017)

poverty_data<-poverty_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                                  variable.name = "Year",
                                          value.name = "Poverty")


poverty_data <- poverty_data %>% arrange(Country.y, Country.x)





#melting gdp data


gdp_data<-select(country, Country.y:Country.x, `Country Code`,
                 gdp_per_capita2002:gdp_per_capita2017)


names(gdp_data)[4:19]=as.character(2002:2017)

gdp_data<-gdp_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                                  variable.name = "Year",
                                  value.name = "GDP")



gdp_data <- gdp_data %>% arrange(Country.y, Country.x)



#melting bribes data
bribe_data<-select(country, Country.y:Country.x, `Country Code`,
                   bribes2017:bribes2010)


names(bribe_data)[4:11]=as.character(2010:2017)

bribe_data<-bribe_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                              variable.name = "Year",
                              value.name = "Bribe")


bribe_data <- bribe_data %>% arrange(Country.y, Country.x)





#melting crime 

crime_data<-select(country, Country.y:Country.x, `Country Code`,
                   organized_crime2017:organized_crime2007)


names(crime_data)[4:14]=as.character(2007:2017)

crime_data<-crime_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                              variable.name = "Year",
                              value.name = "Crime")


crime_data <- crime_data %>% arrange(Country.y, Country.x)










#melting gender data
gender_data<-select(country, Country.x:Country.y, `Country Code`,
                    gender2006:gender2017)


names(gender_data)[4:15]=as.character(2006:2017)

gender_data<-gender_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                                variable.name = "Year",
                                value.name = "Gender")


gender_data <- gender_data %>% arrange(Country.y, Country.x)






#melting tier data
tier_data<-select(country, Country.y:Country.x, `Country Code`,
                  tier2002:tier2017)


names(tier_data)[4:19]=as.character(2002:2017)

tier_data<-tier_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                            variable.name = "Year",
                            value.name = "Tier")


tier_data <- tier_data %>% arrange(Country.y, Country.x)





#melting peace data
peace_data<-select(country, Country.y:Country.x, `Country Code`,
                   peace2008:peace2017)


names(peace_data)[4:13]=as.character(2008:2017)




peace_data<-peace_data%>%melt(id=c("Country.y","Country.x","Country Code"), 
                              variable.name = "Year",
                              value.name = "Peace")


peace_data <- peace_data %>% arrange(Country.y, Country.x)






#creating datsets to merge together
library(plyr)
cdataframes<- list(poverty_data, gdp_data, bribe_data, crime_data, gender_data,
                   peace_data,tier_data)

#creating dataset to merge to exploitation information

country_merge_exp<-join_all(cdataframes,  by=(c("Country.y"="Country.y",
                             "Country.x"="Country.x", "Country Code",
                             "Year"="Year")), type='left')


names(country_merge_exp)[1:2]=c("Country of Exploitation.y", "Country of Exploitation.x")

names(country_merge_exp)[5:11]=c("Exp Poverty", "Exp GDP",
                                 "Exp Bribe", "Exp Crime",
                                 "Exp Gender", "Exp Peace",
                                 "Exp Tier")

#Creating datset to merge to citizenship information
country_merge_citz<-join_all(cdataframes,  by=(c("Country.y"="Country.y",
                             "Country.x"="Country.x", "Country Code",
                             "Year"="Year")), type='left')


names(country_merge_citz)[1:2]=c("Country of Citizenship.y", "Country of Citizenship.x")

names(country_merge_citz)[5:11]=c("Citz Poverty", "Citz GDP",
                                 "Citz Bribe", "Citz Crime",
                                 "Citz Gender", "Citz Peace",
                                 "Citz Tier")








```



#Michael
```{r}


####################

library(tidyverse)
library(tidyr)
library(reshape2)
source(paste(sure_path, '/functions/linearly_interpolate.R', sep = ''))

names(migration)[names(migration) == 'Major area, region, country or area of destination'] <- 'destination'
names(migration)[names(migration) == 'variable'] <- 'origin'
migration_droppedDestNAs <- migration %>% drop_na(destination)
migration_united <- unite(migration_droppedDestNAs, col = "origin_destination", origin, destination, sep = "_")
migration_spread <- spread(migration_united, key = "Year", value = "value")

missingMigyears_vec <- c("1991", "1992", "1993", "1994", "1996", "1997", "1998", "1999", "2001", "2002", "2003", "2004", "2006", "2007", "2008", "2009", "2011", "2012", "2013", "2014", "2016")
for(i in missingMigyears_vec) {
  migration_spread[[i]] <- c(NA)
}
col_order <- c("origin_destination", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017")
migration_spread_ordered <- migration_spread[, col_order]


#List of columns to fill in
migration_full <- linearly_interpolate(migration_spread_ordered, list(2:29))



migration_full_gathered <- migration_full %>% gather("Year", "Value", 2:29)
migration2 <- migration_full_gathered %>% separate(col = "origin_destination", into = c("origin", "destination"), sep = "_")


########################

#install.packages("countrycode")
library(countrycode)
listOfCountryLongNames <- migration2$origin[!duplicated(migration2$origin)]
countryName_vec <- as.vector(listOfCountryLongNames)


#######################

#Convert 2 Letter Country Code of individual$citizenship to Full Country Name and 3 Letter Codes
indvl_2LCCodesCitizen <- individual %>% pull(citizenship) %>% as.vector()
indvl_3LCCodesCitizen <- countrycode(indvl_2LCCodesCitizen, 'genc2c', 'genc3c') %>% as.vector()
indvl_fullCNameCitizen <- countrycode(indvl_2LCCodesCitizen, 'genc2c', 'country.name') %>% as.vector()
multiName_individual <- individual %>% dplyr::mutate(indvl_3LCCodesCitizen, indvl_fullCNameCitizen) %>% select (citizenship, indvl_3LCCodesCitizen, indvl_fullCNameCitizen, everything())

indvl_2LCCodesTraffick <- individual %>% pull(CountryOfExploitation) %>% as.vector()
indvl_3LCCodesTraffick <- countrycode(indvl_2LCCodesTraffick, 'genc2c', 'genc3c') %>% as.vector()
indvl_fullCNameTraffick <- countrycode(indvl_2LCCodesTraffick, 'genc2c', 'country.name') %>% as.vector()
#Adds full name and 3 letter codes of trafficking countries to individual database
manyNames_individual <- multiName_individual %>% dplyr::mutate(indvl_3LCCodesTraffick, indvl_fullCNameTraffick) %>% select(CountryOfExploitation, indvl_3LCCodesTraffick, indvl_fullCNameTraffick, everything())


#####################

#migByCitizCountryToTraffCountryByYear which gives migration from citizenship country to trafficking country in 1990 to 2017
migByCitizCountry <- data.frame()
migByCitizCountry_df <- data.frame()
migByCitizCountryToTraffCountry <- data.frame()
migByCitizCountryToTraffCountry_df <- data.frame()
migByCitizCountryToTraffCountryByYear <- data.frame()
migByCitizCountryToTraffCountryByYear_df <- data.frame()

indvl_fullCNameCitizen_vec <- indvl_fullCNameCitizen[!duplicated(indvl_fullCNameCitizen)] %>% as.vector()
indvl_fullCNameTraffick_vec <- indvl_fullCNameTraffick[!duplicated(indvl_fullCNameTraffick)] %>% as.vector()
yearOfTrafficking_vec <- manyNames_individual %>% pull(yearOfRegistration) %>% as.vector
yearOfTrafficking_vec_NoRep <- yearOfTrafficking_vec[!duplicated(yearOfTrafficking_vec)] %>% as.vector()

for(i in indvl_fullCNameCitizen_vec) {
  migByCitizCountry_df = migration2 %>% filter(origin == i)
  migByCitizCountry = rbind(migByCitizCountry, migByCitizCountry_df)
}

for(j in indvl_fullCNameTraffick_vec) {
  migByCitizCountryToTraffCountry_df = migByCitizCountry %>% filter(destination == j)
  migByCitizCountryToTraffCountry = rbind(migByCitizCountryToTraffCountry, migByCitizCountryToTraffCountry_df)
}
for(k in yearOfTrafficking_vec_NoRep) {
  migByCitizCountryToTraffCountryByYear_df = migByCitizCountryToTraffCountry %>% filter(Year == k)
  migByCitizCountryToTraffCountryByYear = rbind(migByCitizCountryToTraffCountryByYear, migByCitizCountryToTraffCountryByYear_df)
}

####################

  
#migByCitizCountryToWorldByYear which gives the migration from citizenship country to all countries combined in 1990 to 2017
migByCitizCountryToWorld <- data.frame()
migByCitizCountryToWorld_df <- data.frame()
migByCitizCountryToWorldByYear <- data.frame()
migByCitizCountryToWorldByYear_df <- data.frame()

#Gives total migration from all countries to WORLD in 1990 to 2017.
migrationFromAllCountryToWorldBools <- migration2$destination == "WORLD"
migrationFromAllCountryToWorld <- migration2[migrationFromAllCountryToWorldBools, ]

for(i in indvl_fullCNameCitizen_vec) {
  migByCitizCountryToWorld_df = migrationFromAllCountryToWorld %>% filter(origin == i)
  migByCitizCountryToWorld = rbind(migByCitizCountryToWorld, migByCitizCountryToWorld_df)
}
for(j in yearOfTrafficking_vec_NoRep) {
  migByCitizCountryToWorldByYear_df = migByCitizCountryToWorld %>% filter(Year == j)
  migByCitizCountryToWorldByYear = rbind(migByCitizCountryToWorldByYear, migByCitizCountryToWorldByYear_df)
}


##################
#migByWORLDToTraffCountryByYear which gives the total migration from all countries combined to trafficked countries in 1990 to 2017

year_vec <- 1990:2017
migration_counts = data.frame()
for(i in year_vec) {
  df = migration2 %>% filter(Year == i)
  df_phony = data.frame()
  df_mig <- tapply(df$Value, df$destination, sum)
  year <- rep(i, length(df_mig))
  df_phony <- cbind(year, df_mig)
  migration_counts = rbind(migration_counts, df_phony)
}

dest_vec <- vector()
for(i in 1:nrow(migration_counts)) {
  dest_vec <- c(dest_vec, rownames(migration_counts)[i])
}

dest_vec <- gsub('[0-9]+', '', dest_vec)
migration_counts <- migration_counts %>% dplyr::mutate(dest_vec)
colnames(migration_counts)[2:3] <- c("Migration Count from All Countries Combined", "destination")

migration_counts <- migration_counts %>% select("destination", "Migration Count from All Countries Combined", "year")

migByWORLDToTraffCountry_df <- data.frame()
migByWORLDToTraffCountry <- data.frame()
migByWORLDToTraffCountryByYear_df <- data.frame()
migByWORLDToTraffCountryByYear <- data.frame()


for(j in indvl_fullCNameTraffick_vec) {
  migByWORLDToTraffCountry_df = migration_counts %>% filter(destination == j)
  migByWORLDToTraffCountry = rbind(migByWORLDToTraffCountry, migByWORLDToTraffCountry_df)
}

for(k in yearOfTrafficking_vec_NoRep) {
  migByWORLDToTraffCountryByYear_df = migByWORLDToTraffCountry %>% filter(year == k)
  migByWORLDToTraffCountryByYear = rbind(migByWORLDToTraffCountryByYear, migByWORLDToTraffCountryByYear_df)
}

####################

#Mutate the following three dataframes with the manyNames_individual dataframe: 
#1. migByWORLDToTraffCountryByYear which gives the total migration from all countries combined to trafficked countries in 1990 to 2017
#2. migByCitizCountryToWorldByYear which gives the migration from citizenship country to all countries combined in 1990 to 2017
#3. migByCitizCountryToTraffCountryByYear which gives migration from citizenship country to trafficking country in 1990 to 2017

#First, clean up and rename columns in migByCitizCountryToTraffCountryByYear to match with manyNames_individual
colnames(migByCitizCountryToTraffCountryByYear)[1:4] <- c("Country of Citizenship", 
                                                          "Country of Exploitation", 
                                                          "Year of Registration", 
                                                          "Migration Count from Citizenship Country to Country of Exploitation")

#Second, clean up and rename columns in migByCitizCountryToWorldByYear to match with manyNames_individual
#Got rid of column "destination" with NULL command because destination is always WORLD
migByCitizCountryToWorldByYear$destination <- NULL
colnames(migByCitizCountryToWorldByYear)[1:3] <- c("Country of Citizenship", 
                                                   "Year of Registration", 
                                                   "Migration Count from Citizenship Country to All Other Countries Combined")


#Third, clean up and rename columns in migByWORLDToTraffCountryByYear to match with manyNames_individual
colnames(migByWORLDToTraffCountryByYear)[1:3] <- c("Country of Exploitation",
                                                   "Migration Count from All Countries Combined to Country of Exploitation", 
                                                   "Year of Registration")

migByWORLDToTraffCountryByYear$'Year of Registration' <- as.character(migByWORLDToTraffCountryByYear$'Year of Registration')

#Fourth, clean up and rename problematic columns in manyNames_individual
colnames(manyNames_individual)[1:7] <- c("Country of Exploitation (2L)",
                                         "Country of Exploitation (3L)", 
                                         "Country of Exploitation", 
                                         "Country of Citizenship (2L)", 
                                         "Country of Citizenship (3L)", 
                                         "Country of Citizenship", 
                                         "Year of Registration")


#Fifth, left_join manyNames_individual and the datasets of the three migration flows
individual_merge <- manyNames_individual %>% 
  left_join(migByCitizCountryToTraffCountryByYear) %>% 
  left_join(migByCitizCountryToWorldByYear) %>% 
  left_join(migByWORLDToTraffCountryByYear)


View(individual_merge)


#######################



```



#Imani (cont)
```{r}

View(country_merge_exp)
 big_merge <- country_merge_exp %>% right_join(individual_merge, 
                                               by=(c("Country of Exploitation.y"="Country of Exploitation",
                                              "Year"="Year of Registration",
                                              "Country Code"="Country of Exploitation (3L)")))
 
big_merge <- country_merge_citz %>% right_join(big_merge, 
                                       by=(c("Country of Citizenship.y"
                                              ="Country of Citizenship",
                                              "Year"="Year",
                                              "Country Code"="Country of Citizenship (3L)"))) 

View(big_merge)
```

#Michael (cont)
```{r}


library(tidyverse)
library(tidyr)
library(reshape2)
source(paste(sure_path, '/functions/linearly_interpolate.R', sep = ''))


missingPopyears_vec <- c("pop1951", "pop1952", "pop1953", "pop1954", "pop1956", "pop1957", "pop1958", "pop1959", "pop1961", "pop1962", "pop1963", "pop1964", "pop1966", "pop1967", "pop1968", "pop1969", "pop1971", "pop1972", "pop1973", "pop1974", "pop1976", "pop1977", "pop1978", "pop1979", "pop1981", "pop1982", "pop1983", "pop1984", "pop1986", "pop1987", "pop1988", "pop1989", "pop1991", "pop1992", "pop1993", "pop1994", "pop1996", "pop1997", "pop1998", "pop1999", "pop2001", "pop2002", "pop2003", "pop2004", "pop2006", "pop2007", "pop2008", "pop2009", "pop2011", "pop2012", "pop2013", "pop2014", "pop2016", "pop2017")
for(i in missingPopyears_vec) {
  population[[i]] <- c(NA)
}
populationColOrder <- c("ISO 3166-1 numeric code", "Location", "pop1950", "pop1951", "pop1952", "pop1953", "pop1954", "pop1955", "pop1956", "pop1957", "pop1958", "pop1959", "pop1960", "pop1961", "pop1962", "pop1963", "pop1964", "pop1965", "pop1966", "pop1967", "pop1968", "pop1969", "pop1970", "pop1971", "pop1972", "pop1973", "pop1974", "1975", "pop1976", "pop1977", "pop1978", "pop1979", "pop1980", "pop1981", "pop1982", "pop1983", "pop1984", "pop1985", "pop1986", "pop1987", "pop1988", "pop1989", "pop1990", "pop1991", "pop1992", "pop1993", "pop1994", "pop1995", "pop1996", "pop1997", "pop1998", "pop1999", "pop2000", "pop2001", "pop2002", "pop2003", "pop2004", "pop2005", "pop2006", "pop2007", "pop2008", "pop2009", "pop2010", "pop2011", "pop2012", "pop2013", "pop2014", "pop2015", "pop2016", "pop2017")
populationOrdered <- population[, populationColOrder]
colnames(populationOrdered)[28] <- "pop1975"

View(populationOrdered)
#List of columns to fill in with linear interpolation function
population_full <- linearly_interpolate(populationOrdered, list(3:70))


population_full_gathered <- population_full %>% gather("Year", "Population in Year", 3:70)



population_full_gathered$Year <- gsub('[a-z]+', '', population_full_gathered$Year)



#Removing ISO code, not needed it seems.
population_full_gathered$`ISO 3166-1 numeric code` <- NULL



#Filtering out to make population_full_gathered_filterCitiz
popOfCitizCountry_df <- data.frame()
popOfCitizCountry <- data.frame()
popOfCitizCountryByYear_df <- data.frame()
popOfCitizCountryByYear <- data.frame()
population_full_gathered_filterCitizCandYear <- data.frame()

for(i in indvl_fullCNameCitizen_vec) {
  popOfCitizCountry_df = population_full_gathered %>% filter(Location == i)
  popOfCitizCountry = rbind(popOfCitizCountry, popOfCitizCountry_df)
}

for(k in yearOfTrafficking_vec_NoRep) {
  popOfCitizCountryByYear_df = popOfCitizCountry %>% filter(Year == k)
  popOfCitizCountryByYear = rbind(popOfCitizCountryByYear, popOfCitizCountryByYear_df)
}
population_full_gathered_filterCitizCandYear <- popOfCitizCountryByYear

#Filtering out to make population_full_gathered_filterExpl
popOfTraffCountry_df <- data.frame()
popOfTraffCountry <- data.frame()
popOfTraffCountryByYear_df <- data.frame()
popOfTraffCountryByYear <- data.frame()
population_full_gathered_filterTraffCandYear <- data.frame()

for(j in indvl_fullCNameTraffick_vec) {
  popOfTraffCountry_df = population_full_gathered %>% filter(Location == j)
  popOfTraffCountry = rbind(popOfTraffCountry, popOfTraffCountry_df)
}
for(k in yearOfTrafficking_vec_NoRep) {
  popOfTraffCountryByYear_df = popOfTraffCountry %>% filter(Year == k)
  popOfTraffCountryByYear = rbind(popOfTraffCountryByYear, popOfTraffCountryByYear_df)
}
population_full_gathered_filterTraffCandYear <- popOfTraffCountryByYear

#First, rename columns in population_full_gathered_filterCitizCandYear 
colnames(population_full_gathered_filterCitizCandYear)[1] <- "Country of Citizenship.y"
colnames(population_full_gathered_filterCitizCandYear)[2] <- "Year"
colnames(population_full_gathered_filterCitizCandYear)[3] <- "Population in Country of Citizenship"

#Second, rename columns in population_full_gathered_filterTraffCandYear
colnames(population_full_gathered_filterTraffCandYear)[1] <- "Country of Exploitation.y"
colnames(population_full_gathered_filterTraffCandYear)[2] <- "Year"
colnames(population_full_gathered_filterTraffCandYear)[3] <- "Population in Country of Exploitation"





big_merge_dataset <- left_join(big_merge, population_full_gathered_filterCitizCandYear)
big_merge_datasets <- left_join(big_merge_dataset, population_full_gathered_filterTraffCandYear)

     


write.csv(big_merge_datasets, file = paste(sure_path, 
                                         '/data/big_merge_datasets.csv', sep = ''))

save(big_merge_datasets, file = paste(sure_path, 
                                         '/data/big_merge_datasets.Rdata', sep = ''))
#written to the data folder
```



```

