---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(mice)

load("~/code/CMU/sure2018/data/merged_dataset.Rdata")

#mice doesn't like column names with spaces in them
colnames(big_merge_datasets) <- gsub(' ', '_', colnames(big_merge_datasets))


p_mat <- mice(big_merge_datasets, maxit = 0)$predictorMatrix

p_mat_blocks <- mice(big_merge_datasets, maxit = 0, 
                     blocks = list(c("meansOfControlDebtBondage", 
                                     "meansOfControlTakesEarnings",
                                     "meansOfControlRestrictsFinancialAccess",
                                     "meansOfControlThreats",
                                     "meansOfControlPsychologicalAbuse",
                                     "meansOfControlPhysicalAbuse",
                                     "meansOfControlSexualAbuse", 
                                     "meansOfControlFalsePromises",
                                     "meansOfControlPsychoactiveSubstances",
                                     "meansOfControlRestrictsMovement",
                                     "meansOfControlRestrictsMedicalCare",
                                     "meansOfControlExcessiveWorkingHours",
                                     "meansOfControlUsesChildren",
                                     "meansOfControlThreatOfLawEnforcement",
                                     "meansOfControlWithholdsNecessities",
                                     "meansOfControlWithholdsDocuments",
                                     "meansOfControlOther"), "meansOfControlNotSpecified",
                                   c("isForcedLabour", "isSexualExploit", "isOtherExploit",
                                     "isSexAndLabour","isForcedMarriage", "isForcedMilitary", 
                                     "isOrganRemoval" ),
                                   c("typeOfLabourAgriculture", "typeOfLabourAquafarming",
                                     "typeOfLabourBegging", "typeOfLabourConstruction", 
                                     "typeOfLabourDomesticWork", "typeOfLabourHospitality", 
                                     "typeOfLabourIllicitActivities", "typeOfLabourManufacturing",
                                     "typeOfLabourMiningOrDrilling", "typeOfLabourPeddling", 
                                     "typeOfLabourTransportation", "typeOfLabourOther"), 
                                   "typeOfLabourNotSpecified",
                                   c("typeOfSexProstitution", "typeOfSexPornography", 
                                     "typeOfSexRemoteInteractiveServices", 
                                     "typeOfSexPrivateSexualServices"),
                                   c("recruiterRelationIntimatePartner", "recruiterRelationFriend",
                                     "recruiterRelationFamily", "recruiterRelationOther"),
                                   "recruiterRelationUnknown" 
     ))$predictorMatrix

for(i in c(1, 3, 4, 6, 7)) {p_mat_blocks[i, blocks[[i]]] <- 0}
for(i in c(1, 3, 4, 6, 7)) {p_mat[blocks[[i]], blocks[[i]]] <- 0}

#Ensures the variable outside the individual dataset aren't taken into account 
#during imputation
p_mat[, !(colnames(p_mat_blocks) %in% unlist(blocks))] <- 0
p_mat[!(colnames(p_mat_blocks) %in% unlist(blocks)), ] <- 0

p_mat_blocks[, !(colnames(p_mat_blocks) %in% unlist(blocks))] <- 0

mice(data = big_merge_datasets, method = c(rep_len("", 29), rep_len("logreg", 43),
                                           "", rep_len("logreg", 5), rep_len("", 5)),
     predictorMatrix = p_mat)

mice(big_merge_datasets, method = c(rep_len("", 29), rep_len("logreg", 43),
                                           "", rep_len("logreg", 5), rep_len("", 5)),
     predictorMatrix = p_mat_blocks, blocks = list(c("meansOfControlDebtBondage", 
                                     "meansOfControlTakesEarnings",
                                     "meansOfControlRestrictsFinancialAccess",
                                     "meansOfControlThreats",
                                     "meansOfControlPsychologicalAbuse",
                                     "meansOfControlPhysicalAbuse",
                                     "meansOfControlSexualAbuse", 
                                     "meansOfControlFalsePromises",
                                     "meansOfControlPsychoactiveSubstances",
                                     "meansOfControlRestrictsMovement",
                                     "meansOfControlRestrictsMedicalCare",
                                     "meansOfControlExcessiveWorkingHours",
                                     "meansOfControlUsesChildren",
                                     "meansOfControlThreatOfLawEnforcement",
                                     "meansOfControlWithholdsNecessities",
                                     "meansOfControlWithholdsDocuments",
                                     "meansOfControlOther"), "meansOfControlNotSpecified",
                                   c("isForcedLabour", "isSexualExploit", "isOtherExploit",
                                     "isSexAndLabour","isForcedMarriage", "isForcedMilitary", 
                                     "isOrganRemoval" ),
                                   c("typeOfLabourAgriculture", "typeOfLabourAquafarming",
                                     "typeOfLabourBegging", "typeOfLabourConstruction", 
                                     "typeOfLabourDomesticWork", "typeOfLabourHospitality", 
                                     "typeOfLabourIllicitActivities", "typeOfLabourManufacturing",
                                     "typeOfLabourMiningOrDrilling", "typeOfLabourPeddling", 
                                     "typeOfLabourTransportation", "typeOfLabourOther"), 
                                   "typeOfLabourNotSpecified",
                                   c("typeOfSexProstitution", "typeOfSexPornography", 
                                     "typeOfSexRemoteInteractiveServices", 
                                     "typeOfSexPrivateSexualServices"),
                                   c("recruiterRelationIntimatePartner", 
                                     "recruiterRelationFriend",
                                     "recruiterRelationFamily", "recruiterRelationOther"),
                                   "recruiterRelationUnknown"))
```

