---
title: "Prep for Imputation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```







#Loading everything:
```{r}
library(reshape2)
library(tidyverse)
library(mice)

sure_path <- substr(getwd(), 1, nchar(getwd()) - 4)
source(paste(sure_path, "/functions/mice_new.R", sep = ""))
source(paste(sure_path, "/functions/fill_in_nas.R", sep = ""))
source(paste(sure_path, "/functions/some_testing_functions.R", sep = ""))

#put name of data file here:
data_file <- "/merged_dataset.Rdata"
load(paste(sure_path, "/data" , data_file, sep = ""))

```

#some initial clean up of the dataset
```{r}
cols_to_remove <- c("isForcedMilitary","isOrganRemoval","typeOfLabourIllicitActivities",
                    "typeOfLabourMiningOrDrilling","typeOfLabourTransportation",
                    "typeOfSexRemoteInteractiveServices")
# for(i in cols_to_remove){
#   cat(i, "has", row_sum_test(big_merge_datasets, i, 1, equal = TRUE, na.rm = TRUE), 
#       "rows with a 1 in them \n")
# }

#all the columns in cols_to_remove don't have a single one, i.e. these indicators
#are never true, so we removed them
big_merge_datasets[, cols_to_remove] <- NULL

#furthermore the variable isSexAndLabour has a 1 in 23 instances and in each of them
#both isForcedLabour and isSexualExploit have a 1 as well
big_merge_datasets[,"isSexAndLabour"] <- NULL

#mice doesn't like column names with spaces in them
colnames(big_merge_datasets) <- gsub(' ', '_', colnames(big_merge_datasets))

#parentheses makes R try to do a function call
colnames(big_merge_datasets)[22:23] <- c("Country_of_Exploit_2L", "Country_of_Citizenship_2L")
```

#Running fill_in_nas

```{r}


# coln`
# for(i in list(30:46, 48:51, 52:60, 62:64, c(65, 67:70))){
#   cat(i[1], "has", row_sum_test(big_merge_datasets, i, 1, equal = TRUE, na.rm = TRUE), 
#       "rows with a 1 in them \n")
#   cat(i[1], "has", row_sum_test(big_merge_datasets, i, 1, greater_than = TRUE, na.rm = TRUE), 
#       "rows with more than a single 1 in them \n")
# }

#30:46 means
#48:51 is
#52:61 typeOfLabour
#62:64 typeOfSex
#c(65, 66:70) isAbduction/recruiter
for(i in list(30:46, 48:51, 52:60, 62:64, c(65, 67:70))){
  big_merge_datasets <- fill_in_nas(big_merge_datasets, i)
}
```


#Blocks for imputation
```{r}
imp_dataset_names<-colnames(big_merge_datasets)

controlgroup <-  grep("meansOfControl+",imp_dataset_names, value=TRUE)
#take out not specified
control_not_specified <- controlgroup[length(controlgroup)]
controlgroup <- controlgroup[-length(controlgroup)]

recruitergroup <- grep("recruiter+", imp_dataset_names, ignore.case = FALSE, value=TRUE)
#removing not specified
recruiter_not_specified <- recruitergroup[length(recruitergroup)]
recruitergroup <- recruitergroup[-length(recruitergroup)]
recruitergroup <- append(recruitergroup, "isAbduction")


labourgroup <- grep("typeOfLabour+",imp_dataset_names, value=TRUE)
#removing not specified 
labourgroup_not_specified <- labourgroup[length(labourgroup)]
labourgroup <- labourgroup[-length(labourgroup)]
labourgroup <- append(labourgroup, "isForcedLabour")

sexgroup<-grep("typeOfSex+", imp_dataset_names, ignore.case = FALSE, value=TRUE)
sexgroup<-append(sexgroup, c("isSexualExploit","isForcedMarriage"))


block_list<-list(controlgroup, control_not_specified, recruitergroup, recruiter_not_specified,
                 labourgroup, labourgroup_not_specified, sexgroup, "isOtherExploit")
```


#Constructing the predictorMatrix
```{r}
ini <- mice(big_merge_datasets, blocks = block_list, maxit = 0)
pred_matrix <- ini$predictorMatrix
#View(pred_matrix)

pred_matrix[,-(22:72)] <- 0

for(i in 1:length(block_list)){
  pred_matrix[i, block_list[[i]]] <- 0
}
```

#Running mice_new
```{r}
test_run <- mice_new(big_merge_datasets, blocks = block_list, 
                     predictorMatrix = pred_matrix, seed = 1729,
                     m = 5, maxit = 5)

test <- mice_new_cleanup(test_run)

chain_array <- test$mids$chainMean
chain_array2 <- test$mids$chainVar
num_vars <- dim(chain_array)[[1]]
var_names <- dimnames(chain_array)[[1]][sample(num_vars, 10)]
vis_chain(chain_array, var_names) # takes around 15 seconds
vis_chain(chain_array2, var_names) # takes around 15 seconds
```


#Rerunning mice_new with the many of the columns as factors
```{r}

big_merge_datasets_factor <- big_merge_datasets

#converts year and ageBroad into ordered factors
big_merge_datasets_factor$Year <- as.ordered(big_merge_datasets$Year)
big_merge_datasets_factor$ageBroad <- as.ordered(big_merge_datasets$ageBroad)
big_merge_datasets_factor$ageBroad <- fct_relevel(big_merge_datasets$ageBroad, "0--8", "9--17", 
                                   "18--20", "21--23", "24--26", "27--29", 
                                   "30--38", "39--47", "48+")

#converts the columns with characters into unordered factors
factor_cols <- c("Datasource", "gender", "majorityStatus", "majorityEntry",  
                 "RecruiterRelationship",  
                 "meansOfControlDebtBondage", "meansOfControlTakesEarnings", 
                 "meansOfControlRestrictsFinancialAccess", "meansOfControlThreats", 
                 "meansOfControlPsychologicalAbuse", "meansOfControlPhysicalAbuse", 
                 "meansOfControlSexualAbuse", "meansOfControlFalsePromises", 
                 "meansOfControlPsychoactiveSubstances", "meansOfControlRestrictsMovement", 
                 "meansOfControlRestrictsMedicalCare", "meansOfControlExcessiveWorkingHours", 
                 "meansOfControlUsesChildren", "meansOfControlThreatOfLawEnforcement", 
                 "meansOfControlWithholdsNecessities", "meansOfControlWithholdsDocuments", 
                 "meansOfControlOther", "meansOfControlNotSpecified", "isForcedLabour", 
                 "isSexualExploit", "isOtherExploit","isForcedMarriage", 
                 "typeOfLabourAgriculture", "typeOfLabourAquafarming", "typeOfLabourBegging", 
                 "typeOfLabourConstruction", "typeOfLabourDomesticWork", 
                 "typeOfLabourHospitality", "typeOfLabourManufacturing","typeOfLabourPeddling", 
                 "typeOfLabourOther", "typeOfLabourNotSpecified", "typeOfSexProstitution", 
                 "typeOfSexPornography","typeOfSexPrivateSexualServices", 
                 "recruiterRelationIntimatePartner", "recruiterRelationFriend", 
                 "recruiterRelationFamily", "recruiterRelationOther", 
                 "recruiterRelationUnknown", "isAbduction")

for (column in factor_cols) {
  big_merge_datasets_factor[,column] <- as.factor(unlist(big_merge_datasets[,column]))
}

# test_run <- mice_new(big_merge_datasets_factor, 
#                      blocks = block_list, 
#                      predictorMatrix = pred_matrix, seed = 1729,
#                      m = 5, maxit = 5)

#MUST RUN WITH 10 MAXIT AND data_corrected = correct_data(data_proxy, option = "empirical")
#COMPARE THE NAS AFTER DOING THIS TO THE NAS ORIGINALLY
for (column in factor_cols) {
  big_merge_datasets_factor[,column] <- as.factor(unlist(big_merge_datasets[,column]))
}

test_run <- mice_new(big_merge_datasets_factor, 
                     data_corrected = correct_data(data_proxy, option = "empirical"),
                     blocks = block_list, 
                     predictorMatrix = pred_matrix, seed = 1729,
                     m = 5, maxit = 10)

test_factors <- mice_new_cleanup(test_run)

chain_array <- test_factors$mids$chainMean
chain_array2 <- test_factors$mids$chainVar
num_vars <- dim(chain_array)[[1]]
var_names <- dimnames(chain_array)[[1]][sample(num_vars, 10)]
vis_chain(chain_array, var_names) # takes around 15 seconds
vis_chain(chain_array2, var_names) # takes around 15 seconds
```



#Rerunning the mice_new with indicator variables as logicals
```{r}
big_merge_datasets_logical <- big_merge_datasets
#converts year and ageBroad into ordered factors
big_merge_datasets_logical$Year <- as.ordered(big_merge_datasets$Year)
big_merge_datasets_logical$ageBroad <- as.ordered(big_merge_datasets$ageBroad)
big_merge_datasets_logical$ageBroad <- fct_relevel(big_merge_datasets$ageBroad, "0--8", "9--17", 
                                   "18--20", "21--23", "24--26", "27--29", 
                                   "30--38", "39--47", "48+")

#converts the columns with characters into unordered factors
factor_cols <- c("Datasource", "gender", "majorityStatus", "majorityEntry",  
                 "RecruiterRelationship")

logical_cols <- c("meansOfControlDebtBondage", "meansOfControlTakesEarnings", 
                 "meansOfControlRestrictsFinancialAccess", "meansOfControlThreats", 
                 "meansOfControlPsychologicalAbuse", "meansOfControlPhysicalAbuse", 
                 "meansOfControlSexualAbuse", "meansOfControlFalsePromises", 
                 "meansOfControlPsychoactiveSubstances", "meansOfControlRestrictsMovement", 
                 "meansOfControlRestrictsMedicalCare", "meansOfControlExcessiveWorkingHours", 
                 "meansOfControlUsesChildren", "meansOfControlThreatOfLawEnforcement", 
                 "meansOfControlWithholdsNecessities", "meansOfControlWithholdsDocuments", 
                 "meansOfControlOther", "meansOfControlNotSpecified", "isForcedLabour", 
                 "isSexualExploit", "isOtherExploit","isForcedMarriage", 
                 "typeOfLabourAgriculture", "typeOfLabourAquafarming", "typeOfLabourBegging", 
                 "typeOfLabourConstruction", "typeOfLabourDomesticWork", 
                 "typeOfLabourHospitality", "typeOfLabourManufacturing","typeOfLabourPeddling", 
                 "typeOfLabourOther", "typeOfLabourNotSpecified", "typeOfSexProstitution", 
                 "typeOfSexPornography","typeOfSexPrivateSexualServices", 
                 "recruiterRelationIntimatePartner", "recruiterRelationFriend", 
                 "recruiterRelationFamily", "recruiterRelationOther", 
                 "recruiterRelationUnknown", "isAbduction")

for (column in factor_cols) {
  big_merge_datasets_logical[,column] <- as.factor(unlist(big_merge_datasets[,column]))
}

for (column in logical_cols) {
  big_merge_datasets_logical[,column] <- as.logical(unlist(big_merge_datasets[,column]))
}

test_run <- mice_new(big_merge_datasets_factor, blocks = block_list, 
                     predictorMatrix = pred_matrix, seed = 1729,
                     m = 5, maxit = 5)

test_logical <- mice_new_cleanup(test_run)

chain_array <- test_logical$mids$chainMean
chain_array2 <- test_logical$mids$chainVar
num_vars <- dim(chain_array)[[1]]
var_names <- dimnames(chain_array)[[1]][sample(num_vars, 10)]
vis_chain(chain_array, var_names) # takes around 15 seconds
vis_chain(chain_array2, var_names) # takes around 15 seconds

```


#Some tests to see if the results are reasonable 
```{r}
#The number of 1's in each group of variables
row_sum_test(test_factors$mids$data, grep("meansOfControl+",imp_dataset_names, value=TRUE), number = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfLabour+",imp_dataset_names, value=TRUE), number = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfSex+",imp_dataset_names, value=TRUE), number = TRUE)
row_sum_test(test_factors$mids$data, grep("recruiter+",imp_dataset_names, value=TRUE), number = TRUE)


#How many rows have more than one indicator variable flagged for each block:
#meansOfControl*
row_sum_test(test_factors$mids$data, grep("meansOfControl+",imp_dataset_names,
                                value=TRUE), a = 1, greater_than = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfLabour+",imp_dataset_names,
                                value=TRUE), a = 1, greater_than = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfSex+",imp_dataset_names, 
                                value=TRUE), a = 1, greater_than = TRUE)
row_sum_test(test_factors$mids$data, grep("recruiter+",imp_dataset_names,
                                value=TRUE), a = 1, greater_than = TRUE)



#recruiterRelationship*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("recruiter+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("recruiter+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

#typeOfLabour*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("typeOfLabour+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("typeOfLabour+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

#typeOfSex*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("typeOfSex+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("typeOfSex+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) > 1)

#How many rows have less than one indicator variable flagged for each block:
row_sum_test(test_factors$mids$data, grep("meansOfControl+",imp_dataset_names,
                                value=TRUE), a = 1, less_than = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfLabour+",imp_dataset_names,
                                value=TRUE), a = 1, less_than = TRUE)
row_sum_test(test_factors$mids$data, grep("typeOfSex+",imp_dataset_names, 
                                value=TRUE), a = 1, less_than = TRUE)
row_sum_test(test_factors$mids$data, grep("recruiter+",imp_dataset_names,
                                value=TRUE), a = 1, less_than = TRUE)
#
#meansOfControl*
sum(apply(test_factors$mids$data[test_factors$mids$data$meansOfControlNotSpecified == 1, 
                          grep("meansOfControl+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$meansOfControlNotSpecified == 0, 
                          grep("meansOfControl+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)


#recruiterRelationship*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("recruiter+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("recruiter+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

#typeOfLabour*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("typeOfLabour+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("typeOfLabour+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

#typeOfSex*
sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 0, 
                          grep("typeOfSex+", imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)

sum(apply(test_factors$mids$data[test_factors$mids$data$recruiterRelationUnknown == 1, 
                          grep("typeOfSex+",imp_dataset_names, value=TRUE)], 
           MARGIN = 1, function(x){sum(as.numeric(x))}) < 1)
```






